_extends: rokmoln/support-firecloud:repo/dot.github/settings.base.yml

repository:
  name: support-firecloud
  description: Software and configuration that supports various cycles of software development.
