# image: ubuntu:20.04
image: ysoftwareab/yp-ubuntu-20.04-common:latest

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true

vscode:
  extensions:
    # sync with .vscode/extensions:recommended
    - cardinal90.multi-cursor-case-preserve
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.editorconfig
    - glen-84.sass-lint
    - ms-azuretools.vscode-docker
    - ms-vscode-remote.remote-containers
    - ms-vscode.vscode-typescript-tslint-plugin
    - orta.vscode-jest
    - timonwong.shellcheck

# NOTE 'make bootstrap' would be nice because
# the branch's bootstrap might be out of sync with ysoftwareab/yp-ubuntu-20.04-common:latest
# NOTE 'gp env PATH=$PATH' in order for vscode to find brew executable e.g. shellcheck
# TODO should also modify the shell's rc file to source dev/inc.sh

tasks:
  - # init: |
    #   source dev/inc.sh
    #   make bootstrap
    command: |
      source dev/inc.sh
      gp env PATH=$PATH
      gp open README.md
