# 0. Misc
matrix:
  include:
    - name: "Linux Trusty 14.04 with minimal brew"
      os: linux
      dist: trusty
      env: CACHE_NAME=linux-trusty-minimal SF_CI_BREW_INSTALL=minimal

    - name: "Linux Trusty 14.04 with common brew"
      os: linux
      dist: trusty
      env: CACHE_NAME=linux-trusty-common SF_CI_BREW_INSTALL=common
      if: type IN (push, cron)

    - name: "Linux Xenial 16.04 with minimal brew"
      os: linux
      dist: xenial
      env: CACHE_NAME=linux-xenial-minimal SF_CI_BREW_INSTALL=minimal

    - name: "Linux Xenial 16.04 with common brew"
      os: linux
      dist: xenial
      env: CACHE_NAME=linux-xenial-common SF_CI_BREW_INSTALL=common
      if: type IN (push, cron)

    - name: "OSX High Sierra 10.13 (Xcode 10.1) with dev brew"
      os: osx
      osx_image: xcode10.1
      env: CACHE_NAME=osx-xcode10.1-dev SF_CI_BREW_INSTALL=dev
      if: type IN (push, cron)

# 1. Notifications
notifications:
  slack:
    rooms:
      # atex-ci
      - secure: "PHjlBIIt+ggW94UypB1yP/Sjm8eV6jaGkKXtMeRUcs0WY2TV20a/rojlPh90quCtln/DPWI1wuS4UrPsvmy7PtFrRICX6FO+Aoc5fm/SZ7v0wVidcO61ThcM1OHz2F1oXXwxstITKpveBHCsKtYNHFkOzytJO6haZnqWq0klJUU/TfGBvJ+WNIzVKPQc0vbdjRzzUHMkPzZFk7DPRCaWD6/J2rGY+Xm9s1FBbXTpqaj6uAmCU1FeXi/oTKhpIFRrSO8UPxtxQeg45i7GEhq1tB8MW6SrV9oo10iNPrHQ7f8r+qfrIK1RAaL6SfhmB5+ghz1ckOMMgUXyqBkMKMbdf7k98acXAZwkR3IPN/qcSg8Dd2BZVbKArHxTafVppJkjrd3F1Mpq5PW1ON8HqBek0YyrYpadXG9JLaGHK00wbmu6ruX5tdgpTAlboZnV0X/TEgqbC5cZFrAylIV8bQNLEFZf/mdzxPp5SyApO25d/kIwygbC5ysLhWHomsSzA7AC/X28QqlDx37gF75Btd55wSN8TllxA1gQtBjN5C1HMrJ20+b+FBoYBBi1D8IpepgxVeRC63pZvzPGbfNv+MOQLD0yrYaBbg29mKMAs7lerNddAIbJrx3xqaR4xXu0TBUjjLdFULmzySTCjkfeXCUx0FW06D6rAgg1KgYiDZPNo14="
      # cloud-ci
      - secure: "EFN/yGMW+CNrwyqBzJiJOFZIytEIGsz2zBO/s34sCHwk8UukrOJBqSgv1LycjudPr6MizY5ax/IOZkG6fs8ce2Z8qJKNdQC2OHKVXq5Rr5x2HMg3ihoqhEVJhohS2B337TcF6/0WHZ/BT32tOFI1M2Z3WGByxsvrRFTa5eFDxRz+KfyOiWAKjTgY5cG5Sjr3Cmy9vQTFQkWgkSKvIemOCF7q1REFPAg917EvIaZfY2nUT9w9thtvIL3u2JUmWEda+X13oTm5ywEeFo8AYK8CR1PnVfi9O/172Gh8jhPzcjbkl6kEO5E73xPhCAnAoBgIaeQ9cq8kn3uZQeG0cHve55Os8kRGjT/ZFCa/c4XuFkQnLLlNRSJBlQ76EmhU43TianvnwJt/s9H1+ak9pypY5NYe/bx3NMd0BuhkhHB/zcKq96x/ZE7yiJcpsMw+7voVR+CNec4WsrukEDfiily+9A9M9+cB66z25dpsbKIVe6REer+MD9RTwc2n8M00TBmnB14KGQAE8HEXdzTSF5LWcT1T4nxgHeRKMur185KSovAFEB+93CApAN1NU/ooZRqpYkOLd6weDl6c5il4tZ7iPgDmSlLS9a+17lJ4GwNk9pxd398inYV9XSZGF5ZZykSN9LDipdx1VnRrVW/tSS3B9dt6jlvscB5sWbfr9+k5m7o="
    on_success: change
    on_pull_requests: false

# 2. Env
env:
  global:

# 3. Git
# git:
branches:
  only:
    - master

# 4. Bootstrap
# os: linux
# dist: xenial
language: generic
# addons:
before_cache: ./.ci.sh before_cache
cache:
  directories:
    # common
    - $HOME/.local
    - $HOME/.npm
    # darwin
    - $HOME/.homebrew
    - $HOME/Library/Caches/Homebrew
    - $HOME/Library/Caches/pip
    # linux
    - $HOME/.cache/Homebrew
    - $HOME/.cache/pip
    - $HOME/.linuxbrew

# 5. Steps
before_install: ./.ci.sh before_install
install: ./.ci.sh install
before_script: ./.ci.sh before_script
script: ./.ci.sh script
after_success: ./.ci.sh after_success
after_failure: ./.ci.sh after_failure
after_script: ./.ci.sh after_script

# 6. Deploy
before_deploy: ./.ci.sh before_deploy
# deploy:
after_deploy: ./.ci.sh after_deploy
