# Composite Github Action to make 'support-firecloud' scripts available,
# and run a bash script with current working directory set to 'support-firecloud'.
#
# Usage:
# jobs:
#   main:
#     steps:
#       - uses: rokmoln/support-firecloud@master
#         with:
#           shell: bash
#           run: |
#             pwd
#             ls -la
#             bin/github-checkout


name: 'support-firecloud'
description: 'Execute a command'
inputs:
  shell:
    description: Shell
    default: bash
  run:
    description: Script
    default: echo "Hello world"
  debug:
    description: Enable debug, false/true/trace
    default: false
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_CONTEXT_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_CONTEXT_JOB: ${{ toJSON(job) }}
        GITHUB_CONTEXT_STEPS: ${{ toJSON(steps) }}
        GITHUB_CONTEXT_RUNNER: ${{ toJSON(runner) }}
        GITHUB_CONTEXT_STRATEGY: ${{ toJSON(strategy) }}
        GITHUB_CONTEXT_MATRIX: ${{ toJSON(matrix) }}
        # GITHUB_EVENT_NAME: ${{ github.event_name }}
        # FIXME https://github.com/actions/runner/issues/665
        INPUT_DEBUG: ${{ inputs.debug }}
        INPUT_RUN: ${{ inputs.run }}
        INPUT_SHELL: ${{ inputs.shell }}
      run: |
        [[ "${INPUT_DEBUG}" != "trace" ]] || set -x

        # FIXME https://github.com/actions/runner/issues/716
        [[ -d "${GITHUB_ACTION_PATH}" ]] || \
          GITHUB_ACTION_PATH=/__w/_actions/${GITHUB_ACTION_PATH#/home/runner/work/_actions/}

        "${GITHUB_ACTION_PATH}/action.sh"
