# Composite Github Action to make 'support-firecloud' scripts available, and run sub-actions.
# Default sub-action is 'run'.
# NOTE 'debug' action is just an example. Could have been implemented just fine via 'run'.
#
# ## DEBUG ACTION
# jobs:
#   main:
#     steps:
#       - uses: ysoftwareab/yplatform@master
#         with:
#           action: debug
#           xtrace: true/false # optional
#
# ## RUN ACTION
# jobs:
#   main:
#     steps:
#       - uses: ysoftwareab/yplatform@master
#         with:
#           action: run # optional
#           shell: bash # optional
#           run: |
#             echo 'test1'
#             echo 'test2'
#           xtrace: true/false # optional
#

name: 'support-firecloud'
description: 'Execute a command'
inputs:
  action:
    description: Action, debug/run
    default: run

  shell:
    description: Shell
    default: bash
  run:
    description: Script
    required: true
  xtrace:
    description: Enable bash xtrace
    default: false
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_CONTEXT_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_CONTEXT_JOB: ${{ toJSON(job) }}
        GITHUB_CONTEXT_STEPS: ${{ toJSON(steps) }}
        GITHUB_CONTEXT_RUNNER: ${{ toJSON(runner) }}
        GITHUB_CONTEXT_STRATEGY: ${{ toJSON(strategy) }}
        GITHUB_CONTEXT_MATRIX: ${{ toJSON(matrix) }}
        # FIXME https://github.com/actions/runner/issues/665
        INPUT_XTRACE: ${{ inputs.xtrace }}
      run: |
        [[ "${{ inputs.action }}" == "debug" ]] || exit 0
        [[ "${INPUT_XTRACE}" != "true" ]] || set -x

        # FIXME https://github.com/actions/runner/issues/716
        [[ -d "${GITHUB_ACTION_PATH}" ]] || \
          GITHUB_ACTION_PATH=/__w/_actions/${GITHUB_ACTION_PATH#/home/runner/work/_actions/}

        "${GITHUB_ACTION_PATH}/bin/github-action-debug"

    - shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_CONTEXT_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_CONTEXT_JOB: ${{ toJSON(job) }}
        GITHUB_CONTEXT_STEPS: ${{ toJSON(steps) }}
        GITHUB_CONTEXT_RUNNER: ${{ toJSON(runner) }}
        GITHUB_CONTEXT_STRATEGY: ${{ toJSON(strategy) }}
        GITHUB_CONTEXT_MATRIX: ${{ toJSON(matrix) }}
        # GITHUB_EVENT_NAME: ${{ github.event_name }}
        # FIXME https://github.com/actions/runner/issues/665
        INPUT_RUN: ${{ inputs.run }}
        INPUT_SHELL: ${{ inputs.shell }}
        INPUT_XTRACE: ${{ inputs.xtrace }}
      run: |
        [[ "${{ inputs.action }}" == "run" ]] || exit 0
        [[ "${INPUT_XTRACE}" != "true" ]] || set -x

        # FIXME https://github.com/actions/runner/issues/716
        [[ -d "${GITHUB_ACTION_PATH}" ]] || \
          GITHUB_ACTION_PATH=/__w/_actions/${GITHUB_ACTION_PATH#/home/runner/work/_actions/}

        "${GITHUB_ACTION_PATH}/bin/github-action-run"
