version: "{build}"

branches:
  only:
    - master

environment:
  SF_LOG_BOOTSTRAP: "true"
  WSLENV: SF_LOG_BOOTSTRAP

image: Visual Studio 2019
platform: Any CPU

init:
  - git config --global core.autocrlf input

install:
  - git submodule sync
  - git submodule update --init --recursive
  - wsl --user appveyor ./.ci.sh before_install
  - wsl --user appveyor ./.ci.sh install

# before_build:
build_script:
  - wsl --user appveyor ./.ci.sh before_script
  - wsl --user appveyor ./.ci.sh script
# after_build:

# before_test:
# test_script:
# after_test:

on_success:
  - wsl --user appveyor ./.ci.sh after_success
on_failure:
  - wsl --user appveyor ./.ci.sh after_failure
on_finish:
  - wsl --user appveyor ./.ci.sh after_script

# before_deploy:
# deply_script:
# after_deploy:
