# Composite Github Action to debug github environments.
#
# jobs:
#   main:
#     steps:
#       - uses: ysoftwareab/yplatform/.github/actions/debug@master
#         with:
#           file: path/to/file.txt # optional
#           xtrace: true/false # optional

name: 'ysoftwareab/yplatform:debug'
description: 'Debug GitHub environment'
inputs:
  file:
    description: Enable output to file
    default: /dev/null
  xtrace:
    description: Enable bash xtrace
    default: false
runs:
  using: composite
  steps:
    - shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_CONTEXT_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_CONTEXT_JOB: ${{ toJSON(job) }}
        GITHUB_CONTEXT_STEPS: ${{ toJSON(steps) }}
        GITHUB_CONTEXT_RUNNER: ${{ toJSON(runner) }}
        GITHUB_CONTEXT_STRATEGY: ${{ toJSON(strategy) }}
        GITHUB_CONTEXT_MATRIX: ${{ toJSON(matrix) }}
        # GITHUB_EVENT_NAME: ${{ github.event_name }}
        # FIXME https://github.com/actions/runner/issues/665
        INPUT_FILE: ${{ inputs.file }}
        INPUT_XTRACE: ${{ inputs.xtrace }}
      run: |
        [[ "${INPUT_XTRACE}" != "true" ]] || set -x
        "${GITHUB_ACTION_PATH}/../../../bin/github-action-debug" | tee "${INPUT_FILE}"
