name: debug
'on':
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
concurrency:
  group: 'main'
  cancel-in-progress: true
jobs:
  main:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        'runs-on':
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - macos-11
          - macos-12
          - windows-2019
          - windows-2022
    name: '${{ matrix.runs-on }}'
    runs-on: '${{ matrix.runs-on }}'
    steps:
      - uses: ysoftwareab/yplatform@master
        with:
          action: debug
