name: debug
'on':
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
concurrency:
  group: 'main'
  cancel-in-progress: true
jobs:
  main:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        'runs-on':
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - macos-11
          - macos-12
          - windows-2019
          - windows-2022
    name: '${{ matrix.runs-on }}'
    runs-on: '${{ matrix.runs-on }}'
    steps:
      - uses: ysoftwareab/yplatform/.github/actions/debug@master
        with:
          file: debug.new.txt
      - id: cache-keys
        shell: bash
        run: echo ::set-output name=yyyymm::$(/bin/date -u "+%Y%m")
      - id: cache
        uses: actions/cache@v3
        with:
          path: |
            debug.txt
          key: ${{ matrix.runs-on }}-output-${{ steps.cache-keys.output.yyyymm }}-v0
          'restore-keys': |
            ${{ matrix.runs-on }}-output-${{ steps.cache-keys.output.yyyymm }}-v0
      - if: steps.cache.outputs.cache-hit == 'true'
        shell: bash
        run: |
          diff --unified=1000000 debug.txt debug.new.txt
      - shell: bash
        run: |
          mv debug.new.txt debug.txt
