name: main
on:
  push:
    branches: master

jobs:
  main:
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
        sf_ci_brew_install:
          - minimal
          - common
    runs-on: ${{ matrix.os }}
    env:
      SF_CI_BREW_INSTALL: ${{ matrix.sf_ci_brew_install }}
    steps:
      # - run: /support-firecloud/repo/dot.ci.sh sf_ga_checkout
      - uses: actions/checkout@v2
      - name: actions/checkout@v2 submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 \
            submodule update --init --force --recursive --depth=1
      - run: ./.ci.sh before_install
      - run: ./.ci.sh install
      - run: ./.ci.sh before_script
      - run: ./.ci.sh script
      - run: ./.ci.sh after_failure
        if: failure()
      - run: ./.ci.sh after_success
      - run: ./.ci.sh after_script
        if: always()
