name: main
on:
  push:
    branches: master

jobs:
  main-linux-xenial-minimal:
    runs-on: ubuntu-16.04
    env:
      SF_CI_BREW_INSTALL: minimal
    steps:
      # - run: /support-firecloud/repo/dot.ci.sh sf_ga_checkout
      - uses: actions/checkout@v2
      - name: actions/checkout@v2 submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 \
            submodule update --init --force --recursive --depth=1
      - run: ./.ci.sh before_install
      - run: ./.ci.sh install
      - run: ./.ci.sh before_script
      - run: ./.ci.sh script
