name: main
on:
  push:
    branches: master

jobs:
  main-linux-xenial-minimal:
    runs-on: ubuntu-16.04
    env:
      SF_CI_BREW_INSTALL: minimal
    steps:
      - run: ./.ci.sh sf_ga_checkout
      - run: ./.ci.sh before_install
      - run: ./.ci.sh install
      - run: ./.ci.sh before_script
      - run: ./.ci.sh script
