name: main
on:
  push:
    branches: master

jobs:
  - main-linux-xenial-minimal:
    name: test
    runs-on: ubuntu-xenial
    env:
      SF_CI_BREW_INSTALL: minimal
    steps:
      - uses: actions/checkout@v1
      - run: ./.ci.sh before_install
      - run: ./.ci.sh install
      - run: ./.ci.sh before_script
      - run: ./.ci.sh script
