name: tmate
'on':
  workflow_dispatch:
    inputs:
      runs-on:
        description: jobs.main.runs-on
        required: false
        default: ubuntu-latest
jobs:
  main:
    timeout-minutes: 30
    name: 'main-${{ github.event.inputs.runs-on }}'
    runs-on: '${{ github.event.inputs.runs-on }}'
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        # disabled due to https://github.com/mxschmitt/action-tmate/issues/69
        # limit-access-to-actor: true
