name: tmate
'on':
  workflow_dispatch:
    inputs:
      runs-on:
        description: jobs.main.runs-on
        required: false
        default: ubuntu-latest
jobs:
  main:
    timeout-minutes: 30
    name: 'main-${{ github.event.inputs.runs-on }}'
    runs-on: '${{ github.event.inputs.runs-on }}'
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        sudo: false
